### ISSUE TITLE
Issue with waterz package while trying to run neuron segmentation tutorial

### ISSUE THREAD

**Issue by PG-Gu** [zudi-lin/pytorch_connectomics#142]
Dear developers,

Hello!
I'm trying to run the experiment in [neuron segmentation tutorial](https://connectomics.readthedocs.io/en/latest/tutorials/neuron.html)
However I was stuck in the "Get segmentation" section since I met issues with the [waterz package](https://github.com/zudi-lin/waterz).
I'm using Ubuntu 22.04.2 LTS and Python 2.7.18
I succesfully installed the waterz package following the instruction but it reported following error:
`waterz at thresholds [0.1, 0.3, 0.6]
Compiling waterz in /home/wenqi/.cython/inline
Traceback (most recent call last):
  File "snemi_test_seg.py", line 29, in <module>
    aff_threshold=aff_thresholds, gt=seg_gt)
  File "/home/wenqi/miniconda2/envs/waterz/lib/python2.7/site-packages/waterz-0.8-py2.7-linux-x86_64.egg/waterz/seg_waterz.py", line 56, in waterz
    force_rebuild=True)):
  File "/home/wenqi/miniconda2/envs/waterz/lib/python2.7/site-packages/waterz-0.8-py2.7-linux-x86_64.egg/waterz/__init__.py", line 250, in agglomerate
    return __import__(module_name).agglomerate(
ImportError: /home/wenqi/.cython/inline/waterz_bd99d59b2f8e1db6a4d70afd4da36e04.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv`
I wonder if you have any ideas regarding what caused this problem?
Thanks in advance!

**Comment by donglaiw** [comment]
same as #141
