### ISSUE TITLE
RuntimeError: Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string: train in configs/CREMI-Synaptic-Cleft.yaml

### ISSUE THREAD

**Issue by KeeratKG** [zudi-lin/pytorch_connectomics#40]
Hi!

While running the tutorial on Synaptic Cleft Segmentation (https://zudi-lin.github.io/pytorch_connectomics/build/html/tutorials/cremi.html), I encountered the following error:

```
`Traceback (most recent call last):
  File "pytorch_connectomics/scripts/main.py", line 72, in <module>
    main()
  File "pytorch_connectomics/scripts/main.py", line 65, in main
    trainer = Trainer(cfg, mode, args.checkpoint, device)
  File "/n/home11/kguliani/pytorch_connectomics/connectomics/engine/trainer.py", line 29, in _init_
    self.model = build_model(self.cfg, self.device)
  File "/n/home11/kguliani/pytorch_connectomics/connectomics/model/_init_.py", line 27, in build_model
    model = model.to(device)
  File "/n/home11/kguliani/.conda/envs/py3_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 431, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string: train`
```

Steps to reproduce the error in the shell- 
```
`$ srun --pty -p cox -t 2-00:00 --mem 16000 -n 1 --gres=gpu:4 /bin/bash 
 $ module load cuda/9.2.88-fasrc01 cudnn/7.1.4-fasrc01
 $ module load cuda/9.2.88-fasrc01
 $ module load Anaconda/2019.10

 $ source activate py3_torch 

 $ PATH=/usr/local/cuda/bin:$PATH
 $ echo $PATH
 $ CPATH=/usr/local/cuda/include:$CPATH
 $ echo $CPATH

 $ CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -u pytorch_connectomics/scripts/main.py --config-file pytorch_connectomics/configs/CREMI-Synaptic-Cleft.yaml`
```

Additionally, 

`$ python -c 'import torch; print(torch.version.cuda)'
>>> 9.2

$ nvcc --version
>>> 9.2

@zudi-lin Have a look pls

Thanks!

**Comment by zudi-lin** [comment]
Hi @KeeratKG, I ran the step-by-step commands and did not see similar errors. Could you please try the following solutions and see if there is still a problem?

1. Install **your own Anaconda**: https://docs.anaconda.com/anaconda/install/linux/#installation, and then build a new **py3_torch** env.
2. Put CREMI data under **datasets/CREMI/** at the folder you run the training.
3. Allocate CPU memory **at least 40G** (40000M). The dataset is relatively large.
4. Only load CUDA once. **CUDA 10 works for me**: module load cuda/10.0.130-fasrc01 cudnn/7.4.1.5_cuda10.0-fasrc01.

Let me know if it still doesn't work after trying all those solutions.

**Comment by aayushk614** [comment]
@KeeratKG 
Is your device “train” by any chance? As it is not a device name.

**Comment by KeeratKG** [comment]
> @KeeratKG
> Is your device “train” by any chance? As it is not a device name.

No @aayushk614 device is 'cuda'

**Comment by KeeratKG** [comment]
> Hi @KeeratKG, I ran the step-by-step commands and did not see similar errors. Could you please try the following solutions and see if there is still a problem?

@zudi-lin the error persists.

**Comment by KeeratKG** [comment]
Surprisingly, the same issue arises while running the Neuron Segmentation tutorial too (https://zudi-lin.github.io/pytorch_connectomics/build/html/tutorials/snemi.html ). 

I think the problem may lie in the line `mode = 'test' if args.inference else 'train'` in the file scripts/main.py as the code prints right, up to `Device:  cuda`. That may be where the string:train comes from if I'm not wrong. 

Output: 
```
Command line arguments:
Namespace(checkpoint=None, config_file='pytorch_connectomics/configs/SNEMI-Neuron.yaml', inference=False, opts=[])
Configuration details:
AUGMENTOR:
  ELASTIC: True
  ELASTIC_ALPHA: 12.0
  ELASTIC_P: 0.75
  ELASTIC_SIGMA: 4.0
  FLIP: True
  FLIP_DO_ZTRANS: 0
  FLIP_P: 1.0
  GRAYSCALE: True
  GRAYSCALE_P: 0.75
  MISALIGNMENT: True
  MISALIGNMENT_DISPLACEMENT: 16
  MISALIGNMENT_P: 1.0
  MISSINGPARTS: True
  MISSINGPARTS_P: 0.9
  MISSINGSECTION: True
  MISSINGSECTION_P: 0.5
  RESCALE: True
  RESCALE_P: 0.5
  ROTATE: True
  ROTATE_P: 0.1
DATASET:
  DATA_CHUNK_ITER: 1000
  DATA_CHUNK_NUM: [1, 1, 1]
  DATA_CHUNK_NUM_IND: []
  DATA_CHUNK_STRIDE: True
  DATA_INVALID_THRES: [0.0, 0.0]
  DATA_SCALE: [1.0, 1.0, 1.0]
  DO_CHUNK_TITLE: 0
  IMAGE_NAME: image/train-input.tif
  INPUT_PATH: /n/home11/kguliani/datasets/SNEMI/
  LABEL_BINARY: False
  LABEL_EROSION: 0
  LABEL_MAG: 0
  LABEL_NAME: seg/train-labels.tif
  OUTPUT_PATH: outputs/SNEMI/
  PAD_SIZE: [4, 128, 128]
  PRE_LOAD_DATA: [None, None, None]
  REJECT_P: 0.95
  REJECT_SIZE_THRES: 100
  SCALE_FACTOR: [2, 3, 3]
INFERENCE:
  AUG_MODE: mean
  AUG_NUM: 4
  DO_3D: True
  DO_EVAL: True
  IMAGE_NAME: image/test-input.tif
  INPUT_SIZE: [8, 256, 256]
  MODEL_OUTPUT_ID: [None]
  OUTPUT_NAME: result.h5
  OUTPUT_PATH: outputs/SNEMI/test
  OUTPUT_SIZE: [8, 256, 256]
  PAD_SIZE: [8, 64, 64]
  SAMPLES_PER_BATCH: 32
  STRIDE: [4, 128, 128]
  TEST_ID: 0
  TEST_NUM: 1
MODEL:
  ACT_MODE: elu
  ARCHITECTURE: unet_residual_3d
  EMBEDDING: 1
  EXACT: True
  FILTERS: [28, 36, 48, 64, 80]
  FINETUNE: 
  HEAD_DEPTH: 1
  INPUT_SIZE: [8, 256, 256]
  IN_PLANES: 1
  LOSS_OPTION: [['WeightedBCE']]
  LOSS_WEIGHT: [[1.0]]
  NORM_MODE: bn
  OUTPUT_SIZE: [8, 256, 256]
  OUT_PLANES: 3
  PAD_MODE: rep
  PRE_MODEL: 
  PRE_MODEL_ITER: 0
  PRE_MODEL_LAYER: 
  PRE_MODEL_LAYER_SELECT: -1
  REGU_OPT: []
  REGU_WEIGHT: []
  SIZE_MATCH: True
  TARGET_OPT: ['2']
  WEIGHT_OPT: [['1']]
MONITOR:
  ITERATION_NUM: [10, 50]
  LOG_OPT: [1, 1, 0]
  VIS_OPT: [0, 8]
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    CLIP_TYPE: value
    CLIP_VALUE: 1.0
    ENABLED: False
    NORM_TYPE: 2.0
  GAMMA: 0.1
  ITERATION_SAVE: 1000
  ITERATION_STEP: 1
  ITERATION_TOTAL: 40000
  LR_SCHEDULER_NAME: MultiStepLR
  MOMENTUM: 0.9
  SAMPLES_PER_BATCH: 8
  STEPS: (30000, 35000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0
  WEIGHT_DECAY_NORM: 0.0
SYSTEM:
  NUM_CPUS: 4
  NUM_GPUS: 4
Device:  cuda
model:  unet_residual_3d
Traceback (most recent call last):
  File "pytorch_connectomics/scripts/main.py", line 72, in <module>
    main()
  File "pytorch_connectomics/scripts/main.py", line 65, in main
    trainer = Trainer(cfg, mode, args.checkpoint, device)
  File "/n/home11/kguliani/pytorch_connectomics/connectomics/engine/trainer.py", line 29, in __init__
    self.model = build_model(self.cfg, self.device)
  File "/n/home11/kguliani/pytorch_connectomics/connectomics/model/__init__.py", line 27, in build_model
    model = model.to(device)
  File "/n/home11/kguliani/.conda/envs/py3_torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 415, in to
    device, dtype, non_blocking = torch._C._nn._parse_to(*args, **kwargs)
RuntimeError: Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string: train

```

**Comment by KeeratKG** [comment]
It's fixed. There may have been a problem with some specific commit I'd cloned earlier. 
The latest version: `commit e90a2ddc5d191c3c0465bd8a3b7810dca40f2dba` as of June 6 does not have the bug. Other steps are standard. 
Thanks!
